services:
  yt-web-downloader:
    ports: !reset
      - ${PORT}:${PORT}
    labels: 
      - traefik.enable=true
      - traefik.http.services.${SUBDOMAIN}.loadbalancer.server.port=${PORT}
      - traefik.http.routers.${SUBDOMAIN}.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)
      - traefik.http.routers.${SUBDOMAIN}.entrypoints=https
      - traefik.http.routers.${SUBDOMAIN}.tls.certresolver=letsEncrypt
    networks:
      default:
      traefik_external_network:


networks:
  traefik_external_network:
    external: true
